version: '3.7'
services:
  user-service:
    build: ./user-service
    ports:
      - '7071:7071'
    env_file:
      - ./user-service/.env

  post-service:
    build: ./post-service
    ports:
      - '7072:7072'
    env_file:
      - ./post-service/.env

  api-gateway:
    build: ./api-gateway
    ports:
      - '7070:7070'